-- 058 - de partij-entiteit: Mehdi's XX1-laag (meeting 2026-07-07,
-- herbevestigd 2026-07-08). Elke partij (Proximus, een klant, een eigen
-- firma) bestaat bij ons EEN keer met een eigen uniek nummer; de
-- Octopus-relatienummers per boekhouding zijn de tweede laag eronder, en
-- klant/leverancier zijn rollen van dezelfde partij ("het TKN-buro is
-- zowel klant als leverancier; met de unieke nummer hebben we een ding").
--
-- Groepering (keuze Shaniel 2026-07-08): BTW-nummer groepeert hard;
-- zonder BTW groepeert een exact gelijke naam over boekhoudingen heen
-- (aanname: dat is dezelfde persoon). Opbouw en herkoppeling staan in
-- db/seeds/partijen-opbouw.sql en zijn idempotent - na elke herimport
-- van de Octopus-exports opnieuw draaien.

CREATE TABLE kern.partij (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    volgnr         integer GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    naam           text NOT NULL,
    btw_nummer     text NOT NULL DEFAULT '',
    is_intern      boolean NOT NULL DEFAULT false,
    kern_firma_id  uuid REFERENCES kern.firma(id) ON DELETE SET NULL,
    leverancier_id uuid REFERENCES kern.leverancier(id) ON DELETE SET NULL,
    gemaakt_op     timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_partij_btw ON kern.partij (btw_nummer)
    WHERE btw_nummer <> '';
CREATE UNIQUE INDEX ux_partij_naam_kaal ON kern.partij (lower(btrim(naam)))
    WHERE btw_nummer = '';

ALTER TABLE kosten.octopus_relatie
    ADD COLUMN partij_id uuid REFERENCES kern.partij(id) ON DELETE SET NULL;
CREATE INDEX ix_octopus_relatie_partij ON kosten.octopus_relatie (partij_id);

GRANT SELECT ON kern.partij TO portal, communicatie, kosten;

INSERT INTO kern.definitie (sleutel, term, definitie) VALUES
    ('partij', 'Partij',
     'Een klant, leverancier of eigen firma als een entiteit met een eigen uniek nummer, ongeacht in hoeveel Octopus-boekhoudingen hij voorkomt of onder welk relatienummer. Klant en leverancier zijn rollen van dezelfde partij, geen aparte dingen. Groepering: BTW-nummer, of exact dezelfde naam wanneer een BTW-nummer ontbreekt.')
ON CONFLICT (sleutel) DO UPDATE
   SET term = EXCLUDED.term, definitie = EXCLUDED.definitie;
