-- 089: de jobs-laag onder het subdisciplineregister, op ISCO-08 (ILO, dus
-- binnen de VN-lijn van migratie 088). Afspraak uit het overleg van 28-07:
-- onder elke subdiscipline de bijbehorende jobs, met een korte officiele
-- beschrijving "zodat we niet over de beschrijving discuteren", en een link
-- die rechtstreeks naar de beschrijving zelf gaat. Agents landen straks op
-- jobniveau, niet op disciplineniveau.
--
-- Bron per rol: de ISCO-08 unit group (viercijferig). De definitie is een
-- Nederlandse samenvatting in twee zinnen van de officiele ILO-definitie;
-- bron_pagina is de pagina in ISCO-08 Volume 1 (de definitieve ILO-publicatie),
-- zodat de UI met een #page=N-anker rechtstreeks op de officiele beschrijving
-- kan landen.
--
-- Bewuste keuze: rollen zijn classificatie (welke functies horen bij welke
-- subdiscipline), geen organogram en geen personen. Ze gaan daarom NIET in de
-- Second Brain-graaf, dezelfde keuze als eerder voor de disciplines zelf.
-- Koppeling van echte personen aan rollen is een latere, aparte stap.

BEGIN;

-- kern.subdiscipline.code is de natuurlijke sleutel; de koppeltabel verwijst
-- ernaar, dus hij moet uniek afdwingbaar zijn.
CREATE UNIQUE INDEX IF NOT EXISTS subdiscipline_code_uniek
    ON kern.subdiscipline (code);

CREATE TABLE IF NOT EXISTS kern.rol (
    code        text PRIMARY KEY,      -- ISCO-08 unit group, bv '1212'
    naam        text NOT NULL,         -- officiele Engelse ISCO-titel
    definitie   text NOT NULL,         -- NL-samenvatting van de ILO-definitie
    bron        text NOT NULL,         -- 'ISCO-08 <code>'
    bron_pagina integer                -- pagina in ISCO-08 Volume 1
);
COMMENT ON TABLE kern.rol IS
  'Jobs-laag van het disciplineregister: ISCO-08 unit groups (migratie 089).';

CREATE TABLE IF NOT EXISTS kern.subdiscipline_rol (
    subdiscipline_code text NOT NULL REFERENCES kern.subdiscipline (code),
    rol_code           text NOT NULL REFERENCES kern.rol (code),
    PRIMARY KEY (subdiscipline_code, rol_code)
);

-- ------------------------------------------------------------------- rollen
INSERT INTO kern.rol (code, naam, definitie, bron, bron_pagina) VALUES
('1120', 'Managing Directors and Chief Executives',
 'Formuleert en toetst het beleid en geeft de algemene strategische richting van de organisatie, binnen de kaders van het bestuur. Draagt de eindverantwoordelijkheid voor de resultaten.', 'ISCO-08 1120', 102),
('1211', 'Finance Managers',
 'Plant, stuurt en coordineert de financiele huishouding van de organisatie: begroting, boekhouding, rapportering en financiering. Beoordeelt de financiele positie en adviseert de leiding.', 'ISCO-08 1211', 104),
('1212', 'Human Resource Managers',
 'Plant, stuurt en coordineert het personeelsbeleid, de arbeidsverhoudingen en de veiligheid en gezondheid op het werk. Verantwoordelijk voor werving, opleiding, verloning en naleving van het arbeidsrecht.', 'ISCO-08 1212', 104),
('1213', 'Policy and Planning Managers',
 'Plant, stuurt en coordineert de beleidsontwikkeling en strategische planning van de organisatie. Vertaalt doelstellingen naar plannen en adviseert de leiding over de koers.', 'ISCO-08 1213', 104),
('1219', 'Business Services and Administration Managers n.e.c.',
 'Plant, stuurt en coordineert ondersteunende en administratieve diensten die niet elders zijn ingedeeld, waaronder facilitaire diensten. Verantwoordelijk voor de dagelijkse bedrijfsvoering van die diensten.', 'ISCO-08 1219', 105),
('1221', 'Sales and Marketing Managers',
 'Plant, stuurt en coordineert de verkoop- en marketingactiviteiten: assortiment, prijzen, verkoopkanalen en doelstellingen. Bepaalt en bewaakt de commerciele aanpak.', 'ISCO-08 1221', 106),
('1222', 'Advertising and Public Relations Managers',
 'Plant, stuurt en coordineert de reclame-, promotie- en pr-activiteiten van de organisatie. Bewaakt het beeld dat de organisatie naar buiten brengt.', 'ISCO-08 1222', 106),
('1223', 'Research and Development Managers',
 'Plant, stuurt en coordineert de onderzoeks- en ontwikkelactiviteiten van de organisatie of van externe opdrachtgevers. Bepaalt de R&D-agenda en de inzet van mensen en middelen.', 'ISCO-08 1223', 106),
('1321', 'Manufacturing Managers',
 'Plant, stuurt en coordineert de productie: capaciteit, kwaliteit, kosten en levertijden. Verantwoordelijk voor de dagelijkse aansturing van de uitvoering.', 'ISCO-08 1321', 109),
('1324', 'Supply, Distribution and Related Managers',
 'Plant, stuurt en coordineert inkoop, opslag, transport en distributie. Verantwoordelijk voor voorraadbeheer, leveranciersafspraken en de goederenstroom.', 'ISCO-08 1324', 110),
('1330', 'Information and Communications Technology Service Managers',
 'Plant, stuurt en coordineert de ICT-dienstverlening: systemen, netwerken, beveiliging en ondersteuning. Verantwoordelijk voor beschikbaarheid, prioriteiten en het ICT-budget.', 'ISCO-08 1330', 111),
('1412', 'Restaurant Managers',
 'Plant, stuurt en coordineert de horeca- en cateringvoorziening: keuken, bediening en inkoop. Bewaakt kwaliteit, hygiene en kosten van eten en drinken.', 'ISCO-08 1412', 117),
('2133', 'Environmental Protection Professionals',
 'Onderzoekt en beoordeelt milieueffecten en ontwikkelt maatregelen om vervuiling en afval te beperken. Adviseert de organisatie over milieuzorg en duurzaamheid.', 'ISCO-08 2133', 126),
('2141', 'Industrial and Production Engineers',
 'Ontwerpt en verbetert productieprocessen en de inrichting van installaties, met oog voor efficientie, veiligheid en kosten. Analyseert werkmethoden en capaciteit.', 'ISCO-08 2141', 127),
('2149', 'Engineering Professionals n.e.c.',
 'Ingenieurs die niet elders zijn ingedeeld: past ingenieurskennis toe op ontwerp, analyse en advies binnen het eigen vakgebied. Werkt aan technische oplossingen en specificaties.', 'ISCO-08 2149', 130),
('2161', 'Building Architects',
 'Ontwerpt gebouwen, begeleidt de uitwerking en bewaakt het ontwerp tijdens de realisatie. Weegt functionele, esthetische en regelgevende eisen tegen elkaar af.', 'ISCO-08 2161', 133),
('2263', 'Environmental and Occupational Health and Hygiene Professionals',
 'Beoordeelt risico''s voor gezondheid en veiligheid op het werk en ontwerpt preventie- en beschermingsmaatregelen. Adviseert over ergonomie, hygiene en welzijn.', 'ISCO-08 2263', 145),
('2411', 'Accountants',
 'Stelt jaarrekeningen en financiele verslagen op, controleert ze en adviseert over boekhouding, fiscaliteit en interne controle. Omvat ook auditors en belastingaccountants.', 'ISCO-08 2411', 158),
('2421', 'Management and Organization Analysts',
 'Analyseert organisatiestructuren, processen en werkwijzen en adviseert over verbetering. Ondersteunt de leiding bij organisatievraagstukken en risicoanalyses.', 'ISCO-08 2421', 160),
('2422', 'Policy Administration Professionals',
 'Ontwikkelt en beoordeelt beleid en regelingen en adviseert over de toepassing ervan. Begeleidt aanvragen, subsidies en programma''s van overheden en instellingen.', 'ISCO-08 2422', 160),
('2423', 'Personnel and Careers Professionals',
 'Adviseert over werving en selectie, loopbanen, verloning en arbeidsverhoudingen. Analyseert functies en arbeidsmarkt en begeleidt personeelsprocessen.', 'ISCO-08 2423', 160),
('2424', 'Training and Staff Development Professionals',
 'Bepaalt opleidingsbehoeften en ontwerpt, geeft en evalueert opleidings- en ontwikkelprogramma''s. Versterkt de vaardigheden van medewerkers.', 'ISCO-08 2424', 161),
('2431', 'Advertising and Marketing Professionals',
 'Ontwikkelt reclamecampagnes en marketingstrategieen en voert marktonderzoek uit. Analyseert klantgedrag en adviseert over positionering, prijs en promotie.', 'ISCO-08 2431', 162),
('2432', 'Public Relations Professionals',
 'Verzorgt de externe communicatie en de relaties met pers, publiek en belanghebbenden. Bewaakt de reputatie en adviseert over woordvoering.', 'ISCO-08 2432', 162),
('2512', 'Software Developers',
 'Onderzoekt, ontwerpt en bouwt softwaresystemen en onderhoudt ze. Vertaalt eisen naar technische ontwerpen en werkende programmatuur.', 'ISCO-08 2512', 165),
('2514', 'Applications Programmers',
 'Schrijft en onderhoudt programmacode op basis van technische specificaties. Test en corrigeert applicaties.', 'ISCO-08 2514', 166),
('2521', 'Database Designers and Administrators',
 'Ontwerpt, beheert en beveiligt databases en bewaakt de kwaliteit en beschikbaarheid van gegevens. Ondersteunt het gegevensbeheer van de organisatie.', 'ISCO-08 2521', 167),
('2522', 'Systems Administrators',
 'Beheert en onderhoudt servers, systemen en netwerkomgevingen en houdt ze beschikbaar en actueel. Ondersteunt gebruikers en lost verstoringen op.', 'ISCO-08 2522', 167),
('2529', 'Database and Network Professionals n.e.c.',
 'Database- en netwerkspecialisten die niet elders zijn ingedeeld, onder wie specialisten informatiebeveiliging. Beveiligt systemen en gegevens en reageert op incidenten.', 'ISCO-08 2529', 168),
('2611', 'Lawyers',
 'Adviseert over juridische vraagstukken, stelt juridische stukken op en vertegenwoordigt de organisatie in geschillen en procedures. Behandelt contracten en aansprakelijkheid.', 'ISCO-08 2611', 169),
('2619', 'Legal Professionals n.e.c.',
 'Juridische professionals die niet elders zijn ingedeeld, zoals bedrijfsjuristen, compliance-adviseurs en IE-specialisten. Bewaakt naleving en juridische kwaliteit zonder procesvertegenwoordiging.', 'ISCO-08 2619', 170),
('3119', 'Physical and Engineering Science Technicians n.e.c.',
 'Technici die metingen, keuringen en inspecties uitvoeren binnen techniek en productie. Ondersteunt kwaliteitscontrole en conformiteitsbeoordeling.', 'ISCO-08 3119', 185),
('3257', 'Environmental and Occupational Health Inspectors and Associates',
 'Inspecteert werkplekken en processen op veiligheid, gezondheid en milieueisen. Onderzoekt incidenten en ziet toe op naleving van voorschriften.', 'ISCO-08 3257', 204),
('3313', 'Accounting Associate Professionals',
 'Voert boekhoudkundige werkzaamheden uit zoals het bijhouden van rekeningen, afletteren en voorbereiden van rapportages. Ondersteunt debiteuren- en crediteurenbeheer.', 'ISCO-08 3313', 208),
('3322', 'Commercial Sales Representatives',
 'Vertegenwoordigt de organisatie bij het verkopen van goederen en diensten aan bedrijven en instellingen. Onderhoudt klantcontacten en sluit orders af.', 'ISCO-08 3322', 210),
('3323', 'Buyers',
 'Koopt goederen en diensten in voor de organisatie: vraagt offertes op, vergelijkt aanbiedingen en plaatst bestellingen. Bewaakt levering en leveranciersafspraken.', 'ISCO-08 3323', 210),
('3331', 'Clearing and Forwarding Agents',
 'Verzorgt douaneformaliteiten en de expeditie van goederen over de grens. Regelt documenten, aangiften en transportafspraken.', 'ISCO-08 3331', 212),
('3339', 'Business Services Agents n.e.c.',
 'Zakelijke dienstverleners die niet elders zijn ingedeeld, zoals medewerkers die offertes en inschrijvingen voorbereiden. Bemiddelt en handelt zakelijke transacties af.', 'ISCO-08 3339', 213),
('3341', 'Office Supervisors',
 'Geeft leiding aan administratief personeel en organiseert en bewaakt de dagelijkse kantoorwerkzaamheden. Verdeelt werk en lost operationele problemen op.', 'ISCO-08 3341', 214),
('3512', 'ICT User Support Technicians',
 'Helpt gebruikers bij problemen met software, hardware en randapparatuur. Installeert, herstelt en documenteert oplossingen.', 'ISCO-08 3512', 226),
('4110', 'General Office Clerks',
 'Voert algemene administratieve taken uit: registreren, archiveren, gegevens invoeren en correspondentie verwerken. Ondersteunt de dagelijkse kantooradministratie.', 'ISCO-08 4110', 231),
('4222', 'Contact Centre Information Clerks',
 'Beantwoordt vragen van klanten per telefoon of digitaal kanaal en registreert meldingen. Verwijst door naar de juiste dienst of persoon.', 'ISCO-08 4222', 236),
('4225', 'Enquiry Clerks',
 'Beantwoordt vragen van klanten en bezoekers over diensten, producten en procedures, aan een balie of loket. Verstrekt informatie en formulieren.', 'ISCO-08 4225', 237),
('4229', 'Client Information Workers n.e.c.',
 'Klanteninformatiemedewerkers die niet elders zijn ingedeeld, onder wie medewerkers die klachten registreren en afhandelen. Volgt dossiers op en koppelt terug naar de klant.', 'ISCO-08 4229', 238),
('4311', 'Accounting and Bookkeeping Clerks',
 'Registreert financiele transacties, controleert facturen en houdt het grootboek bij. Bereidt betalingen en overzichten voor.', 'ISCO-08 4311', 239),
('4321', 'Stock Clerks',
 'Registreert binnenkomende en uitgaande goederen, houdt de voorraad bij en bereidt zendingen voor. Controleert leveringen tegen bestellingen.', 'ISCO-08 4321', 241),
('4323', 'Transport Clerks',
 'Plant en registreert transporten en volgt zendingen op. Houdt rittenschema''s en vervoersdocumenten bij.', 'ISCO-08 4323', 241),
('4415', 'Filing and Copying Clerks',
 'Archiveert documenten, houdt registraties bij en verzorgt kopieer- en poststromen. Zorgt dat stukken vindbaar en volledig zijn.', 'ISCO-08 4415', 243),
('4416', 'Personnel Clerks',
 'Houdt personeelsdossiers en -registraties bij: dienstverbanden, verlof, uren en mutaties. Bereidt personeelsdocumenten voor.', 'ISCO-08 4416', 243),
('5151', 'Cleaning and Housekeeping Supervisors',
 'Organiseert en controleert de schoonmaak en huishoudelijke diensten in gebouwen. Stuurt schoonmaakpersoneel aan en bewaakt de kwaliteit.', 'ISCO-08 5151', 251),
('5153', 'Building Caretakers',
 'Beheert en onderhoudt gebouwen en houdt toezicht op orde, kleine herstellingen en toegang. Eerste aanspreekpunt voor gebruikers van het gebouw.', 'ISCO-08 5153', 252),
('5414', 'Security Guards',
 'Bewaakt gebouwen en terreinen, controleert toegang en grijpt in bij incidenten. Voert rondes en controles uit.', 'ISCO-08 5414', 269),
('6113', 'Gardeners, Horticultural and Nursery Growers',
 'Legt tuinen en groenvoorzieningen aan en onderhoudt ze. Verzorgt beplanting en buitenruimte.', 'ISCO-08 6113', 275)
ON CONFLICT (code) DO NOTHING;

-- -------------------------------------------------------------- koppelingen
INSERT INTO kern.subdiscipline_rol (subdiscipline_code, rol_code) VALUES
('D1.1', '2423'), ('D1.1', '1212'),
('D1.2', '2423'),
('D1.3', '2423'),
('D1.4', '2424'),
('D1.5', '2263'), ('D1.5', '3257'),
('D1.6', '1212'), ('D1.6', '2423'),
('D1.7', '2423'),
('D1.8', '2423'),
('D1.9', '2423'),
('D1.10', '4416'),
('D2.1', '3322'), ('D2.1', '1221'),
('D2.2', '1221'),
('D2.3', '3339'),
('D2.5', '1221'),
('D2.6', '4110'),
('D3.1', '2431'), ('D3.1', '1222'),
('D3.2', '2431'),
('D3.3', '2431'),
('D3.4', '2431'),
('D3.5', '2432'), ('D3.5', '1222'),
('D4.1', '4311'), ('D4.1', '2411'),
('D4.2', '2411'),
('D4.3', '2411'),
('D4.4', '2411'),
('D4.5', '1211'),
('D4.6', '3313'), ('D4.6', '4311'),
('D4.7', '2411'),
('D5.1', '1321'), ('D5.1', '2141'),
('D5.4', '1219'),
('D5.5', '1321'),
('D6.1', '2619'), ('D6.1', '2611'),
('D6.2', '2611'),
('D6.3', '2619'),
('D6.4', '2619'),
('D6.5', '2619'),
('D6.6', '2619'),
('D6.7', '2619'),
('D6.8', '2611'),
('D6.9', '2619'),
('D7.1', '4222'),
('D7.2', '4229'),
('D7.3', '4229'),
('D7.4', '4225'),
('D7.5', '3512'),
('D8.6', '2512'), ('D8.6', '2514'),
('D8.7', '1330'), ('D8.7', '2522'),
('D9.2', '3323'),
('D9.3', '1324'),
('D9.4', '3323'),
('D9.5', '1324'), ('D9.5', '3323'),
('D9.6', '1324'),
('D9.7', '3323'),
('D9.9', '1324'),
('D9.10', '1324'),
('D10.10', '3119'),
('D11.9', '2421'),
('D11.10', '2411'),
('D11.11', '2421'),
('D12.1', '1120'),
('D12.2', '1120'), ('D12.2', '2619'),
('D12.3', '1213'),
('D12.4', '2619'),
('D12.5', '2411'),
('D12.6', '2432'),
('D12.7', '2421'),
('D12.8', '2133'), ('D12.8', '1213'),
('D12.9', '2411'), ('D12.9', '2133'),
('D13.1', '1330'),
('D13.2', '2521'),
('D13.3', '2521'),
('D14.1', '1219'),
('D14.2', '5153'),
('D14.3', '5151'),
('D14.4', '6113'),
('D14.5', '5414'),
('D14.6', '1412'),
('D14.7', '3512'),
('D14.8', '4415'),
('D14.9', '4110'), ('D14.9', '3341'),
('D14.10', '1219'),
('D15.1', '1223'),
('D15.7', '1223'),
('D15.8', '2149'), ('D15.8', '2161'),
('D15.10', '2619'),
('D15.11', '2422'),
('D16.1', '4323'),
('D16.2', '4321'),
('D16.3', '4321'),
('D16.4', '3331'),
('D16.5', '2421'),
('D16.6', '2133'),
('D17.1', '2529'), ('D17.1', '1330'),
('D17.2', '2529'),
('D17.3', '2529'),
('D17.5', '2529'), ('D17.5', '2512'),
('D17.6', '2529'),
('D17.7', '2529'),
('D17.8', '2529'),
('D17.9', '2529'), ('D17.9', '2522'),
('D17.10', '2529'),
('D17.11', '2619')
ON CONFLICT DO NOTHING;

COMMIT;
