-- 090: de sub-elementen ("wat"-laag) onder de subdisciplines, afspraak uit het
-- overleg van 28-07. Zelfde ontwerpregel als register v3.0: een sub-element
-- bestaat alleen als de VN-bron van de subdiscipline het zelf benoemt (de
-- takenvoorbeelden in UN CBF-tabel 4, de artikelen van de ILO-verdragen, de
-- opsommingen in de UNCITRAL-modelwet, de UNGP-stappen, de beginselen van
-- GA-res. 45/95, enzovoort). Waar de bron niets dieper opsomt, zijn er geen
-- sub-elementen; dat is dan zichtbaar eerlijk in plaats van verzonnen.
-- Naam in het Engels (terminologie), definitie kort Nederlands (hover).

BEGIN;

CREATE TABLE IF NOT EXISTS kern.subelement (
    subdiscipline_code text    NOT NULL REFERENCES kern.subdiscipline (code),
    volgorde           integer NOT NULL,
    naam               text    NOT NULL,
    definitie          text    NOT NULL,
    bron               text    NOT NULL,
    PRIMARY KEY (subdiscipline_code, volgorde)
);
COMMENT ON TABLE kern.subelement IS
  'Sub-elementen (wat-laag) per subdiscipline, alleen wat de VN-bron zelf benoemt (migratie 090).';

INSERT INTO kern.subelement (subdiscipline_code, volgorde, naam, definitie, bron) VALUES
-- D1.1 werving (ILO C181 + eerlijke werving)
('D1.1', 1, 'Private employment agencies', 'Werven via erkende private arbeidsbemiddelaars.', 'ILO C181 art. 1'),
('D1.1', 2, 'No recruitment fees for workers', 'Kandidaten betalen nooit voor hun eigen werving.', 'ILO C181 art. 7'),
('D1.1', 3, 'Protection of applicant data', 'Persoonsgegevens van kandidaten beschermd verwerken.', 'ILO C181 art. 6'),
('D1.1', 4, 'Fair recruitment principles', 'Eerlijke, transparante wervingspraktijken over de hele keten.', 'ILO-beginselen voor eerlijke werving'),
-- D1.2 beloning (C95/C131)
('D1.2', 1, 'Regular payment of wages', 'Loon in wettig betaalmiddel en op vaste tijdstippen.', 'ILO C95 art. 3 en 12'),
('D1.2', 2, 'Protection against deductions', 'Alleen toegestane inhoudingen op het loon.', 'ILO C95 art. 8'),
('D1.2', 3, 'Minimum wage fixing', 'Een stelsel dat minimumlonen vaststelt en bijstelt.', 'ILO C131 art. 1-4'),
-- D1.3 sociale bescherming: de negen takken van C102
('D1.3', 1, 'Medical care', 'Geneeskundige zorg bij ziekte en moederschap.', 'ILO C102 deel II'),
('D1.3', 2, 'Sickness benefit', 'Inkomensvervanging bij ziekte.', 'ILO C102 deel III'),
('D1.3', 3, 'Unemployment benefit', 'Inkomensvervanging bij werkloosheid.', 'ILO C102 deel IV'),
('D1.3', 4, 'Old-age benefit', 'Pensioenuitkering bij ouderdom.', 'ILO C102 deel V'),
('D1.3', 5, 'Employment injury benefit', 'Dekking bij arbeidsongeval en beroepsziekte.', 'ILO C102 deel VI'),
('D1.3', 6, 'Family benefit', 'Tegemoetkoming voor gezinslasten.', 'ILO C102 deel VII'),
('D1.3', 7, 'Maternity benefit', 'Uitkering en zorg bij moederschap.', 'ILO C102 deel VIII'),
('D1.3', 8, 'Invalidity benefit', 'Uitkering bij blijvende arbeidsongeschiktheid.', 'ILO C102 deel IX'),
('D1.3', 9, 'Survivors'' benefit', 'Uitkering voor nabestaanden.', 'ILO C102 deel X'),
-- D1.4 opleiding (C142)
('D1.4', 1, 'Vocational guidance', 'Loopbaaninformatie en studie- en beroepskeuzebegeleiding.', 'ILO C142 art. 3'),
('D1.4', 2, 'Vocational training systems', 'Open en samenhangende stelsels van beroepsopleiding.', 'ILO C142 art. 4'),
('D1.4', 3, 'Training linked to employment', 'Opleidingsbeleid gekoppeld aan werkgelegenheid.', 'ILO C142 art. 1'),
-- D1.5 welzijn en veiligheid (C155/C187)
('D1.5', 1, 'Prevention policy and risk assessment', 'Preventiebeleid met beoordeling van arbeidsrisico''s.', 'ILO C155 art. 4 en 16'),
('D1.5', 2, 'Protective measures and equipment', 'Beschermende maatregelen en middelen op de werkplek.', 'ILO C155 art. 16'),
('D1.5', 3, 'OSH training and instruction', 'Opleiding en instructie over veilig werken.', 'ILO C155 art. 19'),
('D1.5', 4, 'Right to remove from danger', 'Werk neerleggen bij ernstig en dreigend gevaar.', 'ILO C155 art. 13'),
('D1.5', 5, 'Preventive safety culture', 'Een preventieve veiligheids- en gezondheidscultuur.', 'ILO C187 art. 3'),
-- D1.6 sociale dialoog (C87/C98)
('D1.6', 1, 'Freedom of association', 'Vrijheid om organisaties op te richten en te kiezen.', 'ILO C87 art. 2'),
('D1.6', 2, 'Protection against anti-union acts', 'Bescherming tegen antivakbondsdiscriminatie.', 'ILO C98 art. 1'),
('D1.6', 3, 'Promotion of collective bargaining', 'Bevordering van collectief onderhandelen.', 'ILO C98 art. 4'),
-- D1.7 DEI (C100/C111)
('D1.7', 1, 'Equal remuneration for equal work', 'Gelijk loon voor werk van gelijke waarde.', 'ILO C100 art. 2'),
('D1.7', 2, 'Non-discrimination in employment', 'Geen onderscheid in toegang tot werk en beroep.', 'ILO C111 art. 1-2'),
('D1.7', 3, 'Protected grounds', 'Ras, kleur, geslacht, godsdienst, overtuiging, afkomst.', 'ILO C111 art. 1'),
-- D1.8 werk-prive (C156/C183)
('D1.8', 1, 'Workers with family responsibilities', 'Werk en gezinstaken combineren zonder nadeel.', 'ILO C156 art. 3'),
('D1.8', 2, 'Maternity leave and benefits', 'Moederschapsverlof met uitkering.', 'ILO C183 art. 4 en 6'),
('D1.8', 3, 'Employment protection', 'Ontslagbescherming en terugkeer na verlof.', 'ILO C183 art. 8-9'),
-- D1.9 meldkanalen (C190/UNGP)
('D1.9', 1, 'Prohibition of violence and harassment', 'Verbod op geweld en intimidatie op het werk.', 'ILO C190 art. 4'),
('D1.9', 2, 'Complaint mechanisms and remedies', 'Meldwegen, klachtbehandeling en herstel.', 'ILO C190 art. 10'),
('D1.9', 3, 'Operational grievance mechanism', 'Een klachtenmechanisme op organisatieniveau.', 'UNGP 29'),
('D1.9', 4, 'Effectiveness criteria', 'Legitiem, toegankelijk, voorspelbaar en billijk.', 'UNGP 31'),
-- D1.10 personeelsadministratie (C160/CBF)
('D1.10', 1, 'Employment and hours records', 'Registratie van dienstverbanden en arbeidstijd.', 'ILO C160 art. 5'),
('D1.10', 2, 'Earnings records', 'Registratie van lonen en loonkosten.', 'ILO C160 art. 5'),
('D1.10', 3, 'HR management activities', 'Ondersteunende personeelsadministratie.', 'UN CBF 2.1.1'),
-- D2 verkoop
('D2.1', 1, 'Activities of sales agents', 'Verkoop via handelsagenten en vertegenwoordigers.', 'UN CBF 2.4.2'),
('D2.1', 2, 'Retail and wholesale trade', 'Verkoop via detail- en groothandelskanalen.', 'UN CBF 2.4.2'),
('D2.2', 1, 'Market strategy planning', 'Marktstrategie en verkoopprogramma''s uitzetten.', 'ISCO-08 1221'),
('D2.2', 2, 'New markets and propositions', 'Nieuwe markten, segmenten en klantrelaties openen.', 'ISCO-08 122'),
('D2.3', 1, 'Preparation of submissions', 'Inschrijvingen opstellen en tijdig indienen.', 'UNCITRAL modelwet aanbesteding art. 40'),
('D2.3', 2, 'Tender securities', 'Zekerheden stellen bij een inschrijving.', 'UNCITRAL modelwet aanbesteding art. 17'),
('D2.5', 1, 'Offer and price', 'Een bepaalbaar aanbod met prijs uitbrengen.', 'CISG art. 14'),
('D2.5', 2, 'Payment terms', 'Betalingsverplichtingen en -momenten afspreken.', 'CISG art. 53-59'),
('D2.5', 3, 'Delivery terms', 'Plaats en moment van levering vastleggen.', 'CISG art. 31-33'),
('D2.6', 1, 'Electronic records and contracting', 'Rechtsgeldige elektronische orders en dossiers.', 'UNCITRAL modelwet elektronische handel art. 5 en 11'),
('D2.6', 2, 'Lawful customer data files', 'Klantgegevens rechtmatig en doelgebonden bijhouden.', 'GA-res. 45/95 beginsel 1-3'),
-- D3 marketing
('D3.1', 1, 'Advertising', 'Commerciele boodschappen ontwikkelen en plaatsen.', 'UN CBF 2.4.1'),
('D3.1', 2, 'Media representation', 'Mediaruimte inkopen en vertegenwoordigen.', 'UN CBF 2.4.1'),
('D3.2', 1, 'Market research', 'Onderzoek naar markt en klantgedrag.', 'UN CBF 2.4.1'),
('D3.2', 2, 'Public opinion polling', 'Peilingen naar opinie en perceptie.', 'UN CBF 2.4.1'),
('D3.3', 1, 'Market strategy and product mix', 'Positionering via strategie, assortiment en prijs.', 'ISCO-08 1221'),
('D3.4', 1, 'Fair e-commerce practices', 'Eerlijke online handel richting consumenten.', 'UNGCP elektronische handel'),
('D3.4', 2, 'Consent and lawful data use', 'Toestemming en rechtmatig gebruik van klantdata.', 'GA-res. 45/95 beginsel 1-3'),
('D3.5', 1, 'Public relations programmes', 'PR-programma''s opzetten en uitvoeren.', 'ISCO-08 1222'),
('D3.5', 2, 'Press and information', 'Pers- en informatievoorziening verzorgen.', 'ISCO-08 1222'),
-- D4 finance
('D4.1', 1, 'Bookkeeping', 'Dagelijkse registratie van transacties.', 'UN CBF 2.1.2'),
('D4.1', 2, 'Accounting', 'Verwerking tot rekeningen en overzichten.', 'UN CBF 2.1.2'),
('D4.2', 1, 'Balance sheet', 'De balans als kernoverzicht.', 'UNCTAD-ISAR SMEGA'),
('D4.2', 2, 'Income statement', 'De resultatenrekening als kernoverzicht.', 'UNCTAD-ISAR SMEGA'),
('D4.2', 3, 'Notes and disclosures', 'Toelichtingen bij de cijfers.', 'UNCTAD-ISAR SMEGA'),
('D4.3', 1, 'Governance disclosures', 'Governance-informatie in het jaarverslag.', 'UNCTAD-ISAR richtsnoeren governance-verslaggeving'),
('D4.4', 1, 'Statutory audit support', 'Voorbereiding en begeleiding van de externe controle.', 'UN CBF 2.1.2'),
('D4.5', 1, 'Banking and financing relations', 'Bankzaken, leasing en financiering.', 'UN CBF 2.1.1'),
('D4.6', 1, 'Receivables and payables records', 'Debiteuren- en crediteurenadministratie.', 'UNCTAD-ISAR SMEGA'),
('D4.6', 2, 'Payment collection', 'Inning van betalingen onder koopcontracten.', 'CISG art. 53-59'),
('D4.7', 1, 'Treaty application', 'Toepassing van belastingverdragen.', 'UN-modelverdrag dubbele belasting (2021)'),
('D4.7', 2, 'Transfer pricing documentation', 'Onderbouwing van interne verrekenprijzen.', 'UN Practical Manual on Transfer Pricing'),
-- D5 operations
('D5.1', 1, 'Production planning and control', 'Plannen en bewaken van de uitvoering.', 'ISCO-08 1321'),
('D5.1', 2, 'Budgets and resources', 'Middelen en budgetten voor de operatie.', 'ISCO-08 1321'),
('D5.4', 1, 'Internal versus external sourcing', 'Zelf doen of uitbesteden aan derden.', 'UN CBF-handboek F.125 fig. 1'),
('D5.4', 2, 'Domestic versus international sourcing', 'Binnenlands of internationaal laten uitvoeren.', 'UN CBF-handboek F.125 fig. 1'),
('D5.5', 1, 'Production of goods', 'De goederenkant van de kernfunctie.', 'UN CBF 1'),
('D5.5', 2, 'Provision of services', 'De dienstenkant van de kernfunctie.', 'UN CBF 2'),
-- D6 legal
('D6.1', 1, 'Contract drafting and review', 'Contracten opstellen en beoordelen.', 'UN CBF 2.1.2'),
('D6.1', 2, 'Formation of contract', 'Aanbod en aanvaarding tot een geldig contract.', 'CISG deel II'),
('D6.1', 3, 'Obligations and remedies', 'Verplichtingen en rechtsmiddelen bij niet-nakoming.', 'CISG deel III'),
('D6.2', 1, 'Formation and registration', 'Oprichting en registratie van de onderneming.', 'UNCITRAL wetgevingsgids besloten ondernemingsvormen'),
('D6.2', 2, 'Members and management', 'Afspraken over vennoten en bestuur.', 'UNCITRAL wetgevingsgids besloten ondernemingsvormen'),
('D6.3', 1, 'Internal compliance controls', 'Interne controles die naleving borgen.', 'UNCAC art. 12(2)(b)'),
('D6.4', 1, 'Codes of conduct', 'Gedragscodes voor de eigen organisatie.', 'UNCAC art. 12(2)(b)'),
('D6.4', 2, 'Anti-corruption commitment', 'Werken tegen corruptie in al haar vormen.', 'UN Global Compact beginsel 10'),
('D6.5', 1, 'Private sector bribery offences', 'Omkoping in de private sector strafbaar.', 'UNCAC art. 21'),
('D6.5', 2, 'Books and records integrity', 'Geen off-book-rekeningen of valse stukken.', 'UNCAC art. 12(3)'),
('D6.6', 1, 'Protection of reporting persons', 'Bescherming van melders tegen benadeling.', 'UNCAC art. 33'),
('D6.7', 1, 'Trademark protection', 'Merken deponeren en internationaal registreren.', 'WIPO: Verdrag van Parijs en Madrid'),
('D6.7', 2, 'Patent filing', 'Octrooien internationaal aanvragen.', 'WIPO PCT'),
('D6.8', 1, 'Arbitration', 'Geschillen beslechten via arbitrage.', 'UNCITRAL modelwet arbitrage'),
('D6.8', 2, 'Mediated settlements', 'Bemiddelde schikkingen internationaal afdwingbaar.', 'Verdrag van Singapore inzake mediation'),
('D6.9', 1, 'Lawfulness and fairness', 'Rechtmatige en eerlijke verwerking.', 'GA-res. 45/95 beginsel 1'),
('D6.9', 2, 'Purpose specification', 'Doelbinding van persoonsbestanden.', 'GA-res. 45/95 beginsel 3'),
('D6.9', 3, 'Access by data subjects', 'Inzage en correctie door betrokkenen.', 'GA-res. 45/95 beginsel 4'),
('D6.9', 4, 'Security of files', 'Beveiliging van persoonsbestanden.', 'GA-res. 45/95 beginsel 7'),
-- D7 klantenservice
('D7.1', 1, 'Call centre operations', 'Klantcontact via callcenter en kanalen.', 'UN CBF 2.4.1'),
('D7.2', 1, 'Complaint handling', 'Klachten registreren en oplossen.', 'UNGCP geschillenbeslechting en verhaal'),
('D7.2', 2, 'Alternative dispute resolution', 'Buitengerechtelijke geschillenbeslechting.', 'UNGCP geschillenbeslechting en verhaal'),
('D7.2', 3, 'Redress mechanisms', 'Herstel en compensatie voor consumenten.', 'UNGCP geschillenbeslechting en verhaal'),
('D7.3', 1, 'Quality and safety standards', 'Kwaliteits- en veiligheidseisen aan het aanbod.', 'UNGCP kwaliteit en veiligheid'),
('D7.4', 1, 'Consumer information', 'Duidelijke informatie voor een geinformeerde keuze.', 'UNGCP consumenteninformatie'),
('D7.4', 2, 'Consumer education', 'Voorlichting over rechten en gebruik.', 'UNGCP consumenteninformatie'),
('D7.5', 1, 'After-sales services', 'Nazorg en ondersteuning na levering.', 'UN CBF 2.4.1'),
-- D8 IT
('D8.6', 1, 'Computer programming', 'Programmeren en aanverwante bouwtaken.', 'UN CBF 2.3.2'),
('D8.7', 1, 'Software publishing and consultancy', 'Softwarelevering en ICT-advies.', 'UN CBF 2.3.1'),
('D8.7', 2, 'Telecommunications', 'Telefonie- en verbindingsdiensten.', 'UN CBF 2.3.1'),
('D8.7', 3, 'Data processing and hosting', 'Dataverwerking, hosting en portalen.', 'UN CBF 2.3.1'),
('D8.7', 4, 'Installation and maintenance', 'Installatie en onderhoud van systemen.', 'UN CBF 2.3.1'),
-- D9 inkoop (modelwet)
('D9.2', 1, 'Technical specifications', 'Objectieve beschrijving van het gevraagde.', 'UNCITRAL modelwet aanbesteding art. 10'),
('D9.2', 2, 'Equal access rules', 'Specificaties zonder onnodige drempels.', 'UNCITRAL modelwet aanbesteding art. 10'),
('D9.3', 1, 'Open tendering', 'Openbare aanbesteding als hoofdmethode.', 'UNCITRAL modelwet aanbesteding hoofdstuk II'),
('D9.3', 2, 'Restricted tendering', 'Aanbesteding met beperkte deelname.', 'UNCITRAL modelwet aanbesteding hoofdstuk II'),
('D9.3', 3, 'Request for quotations', 'Offerteaanvraag voor eenvoudige inkopen.', 'UNCITRAL modelwet aanbesteding hoofdstuk II'),
('D9.3', 4, 'Request for proposals', 'Voorstellenprocedure met dialoog of onderhandeling.', 'UNCITRAL modelwet aanbesteding hoofdstuk II'),
('D9.3', 5, 'Single-source procurement', 'Een-op-een gunning in uitzonderingsgevallen.', 'UNCITRAL modelwet aanbesteding hoofdstuk II'),
('D9.4', 1, 'Supplier qualification criteria', 'Geschiktheid en betrouwbaarheid toetsen.', 'UNCITRAL modelwet aanbesteding art. 9'),
('D9.5', 1, 'Evaluation criteria', 'Vooraf bekendgemaakte beoordelingscriteria.', 'UNCITRAL modelwet aanbesteding art. 11'),
('D9.5', 2, 'Abnormally low submissions', 'Onderzoek naar abnormaal lage inschrijvingen.', 'UNCITRAL modelwet aanbesteding art. 20'),
('D9.6', 1, 'Closed framework agreements', 'Raamovereenkomst met vaste deelnemers.', 'UNCITRAL modelwet aanbesteding hoofdstuk VII'),
('D9.6', 2, 'Open framework agreements', 'Raamovereenkomst met open toetreding.', 'UNCITRAL modelwet aanbesteding hoofdstuk VII'),
('D9.6', 3, 'Second-stage competition', 'Mini-competitie binnen de raamovereenkomst.', 'UNCITRAL modelwet aanbesteding hoofdstuk VII'),
('D9.7', 1, 'Payment and taking delivery', 'Betalen en afnemen volgens contract.', 'CISG art. 53-60'),
('D9.9', 1, 'Payment obligations', 'Correct en tijdig betalen van leveranciers.', 'CISG art. 53-59'),
('D9.9', 2, 'Responsibility in relationships', 'Verantwoordelijkheid in zakelijke relaties.', 'UNGP 13(b)'),
('D9.10', 1, 'Due diligence in sourcing', 'Mensenrechten-due-diligence bij inkoop.', 'UNGP 17'),
('D9.10', 2, 'Sustainable procurement criteria', 'Duurzaamheidscriteria in de inkoop.', 'UNEP-richtsnoeren duurzaam inkopen'),
-- D10 kwaliteit (UNIDO QI: de vijf pijlers)
('D10.10', 1, 'Standards', 'Normen als afspraak over kwaliteit.', 'UNIDO Quality Infrastructure-kader'),
('D10.10', 2, 'Metrology', 'Meetnauwkeurigheid en kalibratie.', 'UNIDO Quality Infrastructure-kader'),
('D10.10', 3, 'Accreditation', 'Bevoegdverklaring van keurende instellingen.', 'UNIDO Quality Infrastructure-kader'),
('D10.10', 4, 'Certification', 'Certificatie tegen normen.', 'UNIDO Quality Infrastructure-kader'),
('D10.10', 5, 'Inspection', 'Keuring en inspectie van producten en diensten.', 'UNIDO Quality Infrastructure-kader'),
-- D11 risico
('D11.9', 1, 'Internal auditing controls', 'Interne controlemaatregelen in de organisatie.', 'UNCAC art. 12(2)(f)'),
('D11.9', 2, 'Books and records', 'Betrouwbare administratie als controlebasis.', 'UNCAC art. 12(3)'),
('D11.10', 1, 'Independent internal audit', 'Onafhankelijke toetsing van de beheersing.', 'UNCAC art. 12(2)(f)'),
('D11.11', 1, 'Understanding disaster risk', 'Risicobeeld van ernstige verstoringen.', 'Sendai-raamwerk prioriteit 1'),
('D11.11', 2, 'Resilience and continuity', 'Veerkracht en continuiteitsvoorzieningen.', 'Sendai-raamwerk prioriteit 3'),
('D11.11', 3, 'Recovery and build back better', 'Herstel dat de organisatie sterker maakt.', 'Sendai-raamwerk prioriteit 4'),
-- D12 strategie en governance
('D12.1', 1, 'Strategy and policy formulation', 'Strategie en beleid vormgeven en toetsen.', 'ISCO-08 1120'),
('D12.1', 2, 'Overall direction', 'De algemene koers van de organisatie.', 'ISCO-08 1120'),
('D12.2', 1, 'Board composition', 'Samenstelling en onafhankelijkheid van het bestuur.', 'UNCTAD-ISAR richtsnoeren governance-verslaggeving'),
('D12.2', 2, 'Ownership structure', 'Eigendoms- en zeggenschapsstructuur.', 'UNCTAD-ISAR richtsnoeren governance-verslaggeving'),
('D12.2', 3, 'Board committees', 'Comites en hun mandaten.', 'UNCTAD-ISAR richtsnoeren governance-verslaggeving'),
('D12.3', 1, 'Information to the board', 'Wat het bestuur wanneer moet weten.', 'UNCTAD-ISAR richtsnoeren governance-verslaggeving'),
('D12.4', 1, 'Identify and assess impacts', 'Nadelige gevolgen opsporen en beoordelen.', 'UNGP 18'),
('D12.4', 2, 'Integrate and act', 'Bevindingen verankeren en maatregelen nemen.', 'UNGP 19'),
('D12.4', 3, 'Track effectiveness', 'Werking van maatregelen volgen.', 'UNGP 20'),
('D12.4', 4, 'Communicate externally', 'Extern verantwoorden over de aanpak.', 'UNGP 21'),
('D12.5', 1, 'Internal control over reporting', 'Beheersing van de verslaggevingskwaliteit.', 'UNCTAD-ISAR richtsnoeren governance-verslaggeving'),
('D12.6', 1, 'Stakeholder consultation', 'Betekenisvol overleg met belanghebbenden.', 'UNGP 18'),
('D12.7', 1, 'Selection of material indicators', 'Kiezen wat er werkelijk toe doet.', 'UNCTAD-ISAR GCI'),
('D12.8', 1, 'SDG prioritisation', 'Prioriteiten kiezen binnen de SDG''s.', 'Agenda 2030 (GA-res. 70/1)'),
('D12.8', 2, 'Ten principles commitment', 'De tien beginselen als ondergrens.', 'UN Global Compact'),
('D12.9', 1, 'Economic indicators', 'Economische kernindicatoren.', 'UNCTAD-ISAR GCI'),
('D12.9', 2, 'Environmental indicators', 'Milieukernindicatoren.', 'UNCTAD-ISAR GCI'),
('D12.9', 3, 'Social indicators', 'Sociale kernindicatoren.', 'UNCTAD-ISAR GCI'),
('D12.9', 4, 'Institutional indicators', 'Institutionele kernindicatoren.', 'UNCTAD-ISAR GCI'),
-- D13 data
('D13.1', 1, 'Data governance policy', 'Beleid en rollen voor gegevensbeheer.', 'UNESCO-aanbeveling AI-ethiek (2021)'),
('D13.2', 1, 'Accuracy of files', 'Juistheid en actualiteit van bestanden.', 'GA-res. 45/95 beginsel 2'),
('D13.3', 1, 'Purpose and content of files', 'Doel en inhoud van persoonsbestanden vastleggen.', 'GA-res. 45/95 beginsel 3 en 8'),
('D13.6', 1, 'Ethical impact assessment', 'Ethische impactbeoordeling van AI-inzet.', 'UNESCO-aanbeveling AI-ethiek (2021)'),
('D13.6', 2, 'Safe and trustworthy AI', 'Veilige, betrouwbare AI-systemen.', 'GA-res. 78/265'),
('D13.6', 3, 'AI capacity building', 'Bekwaamheid van gebruikers en beheerders.', 'UNESCO-aanbeveling AI-ethiek (2021)'),
-- D14 facilities (CBF-voorbeelden)
('D14.1', 1, 'Real estate rental', 'Huur en verhuur van ruimte.', 'UN CBF 2.6.1'),
('D14.2', 1, 'Maintenance and repair', 'Onderhoud en herstel van gebouw en middelen.', 'UN CBF 2.6.2'),
('D14.3', 1, 'Cleaning services', 'Schoonmaak van gebouwen en ruimten.', 'UN CBF 2.6.1'),
('D14.4', 1, 'Landscape services', 'Groenvoorziening en terreinonderhoud.', 'UN CBF 2.6.1'),
('D14.5', 1, 'Security services', 'Bewaking en toegangscontrole.', 'UN CBF 2.6.3'),
('D14.6', 1, 'Food and beverage services', 'Catering en drankvoorziening.', 'UN CBF 2.6.1'),
('D14.7', 1, 'Computer installation', 'Installatie van werkplekapparatuur.', 'UN CBF 2.3.1'),
('D14.7', 2, 'System maintenance and repair', 'Onderhoud en herstel van werkpleksystemen.', 'UN CBF 2.3.1'),
('D14.8', 1, 'Postal services', 'Post- en pakketstromen.', 'UN CBF 2.5.1'),
('D14.8', 2, 'Office administration', 'Documentstromen en kantooradministratie.', 'UN CBF 2.1.2'),
('D14.9', 1, 'Business support services', 'Algemene ondersteunende administratie.', 'UN CBF 2.1.2'),
('D14.10', 1, 'Facility management coordination', 'Regie over facilitaire diensten.', 'UN CBF 2.6.1'),
-- D15 R&D
('D15.1', 1, 'Research policy and funding', 'Beleid en middelen voor onderzoek.', 'UNESCO-aanbeveling wetenschap (2017)'),
('D15.7', 1, 'Natural sciences and engineering R&D', 'Onderzoek in natuurwetenschap en techniek.', 'UN CBF 2.2.2'),
('D15.7', 2, 'Social sciences and humanities R&D', 'Onderzoek in sociale en geesteswetenschappen.', 'UN CBF 2.2.2'),
('D15.8', 1, 'Architectural and engineering tasks', 'Architectuur- en ingenieurswerk.', 'UN CBF 2.2.1'),
('D15.8', 2, 'Technical analysis', 'Technische analyse en beproeving.', 'UN CBF 2.2.1'),
('D15.10', 1, 'Patent portfolio', 'Octrooiportefeuille opbouwen en beheren.', 'WIPO PCT'),
('D15.10', 2, 'Trademark portfolio', 'Merkenportefeuille opbouwen en beheren.', 'WIPO: Verdrag van Parijs en Madrid'),
('D15.11', 1, 'International cooperation', 'Internationale onderzoekssamenwerking.', 'UNESCO-aanbeveling wetenschap (2017)'),
('D15.11', 2, 'Research funding applications', 'Externe financiering voor innovatie.', 'UNESCO-aanbeveling wetenschap (2017)'),
-- D16 keten
('D16.1', 1, 'Road, water, rail and air transport', 'Vervoer over weg, water, spoor en lucht.', 'UN CBF 2.5.1'),
('D16.1', 2, 'Passenger and cargo transport', 'Personen- en goederenvervoer.', 'UN CBF 2.5.1'),
('D16.2', 1, 'Warehousing and storage', 'Magazijnbeheer en opslag.', 'UN CBF 2.5.2'),
('D16.3', 1, 'Packaging', 'Verpakken en verzendklaar maken.', 'UN CBF 2.5.2'),
('D16.4', 1, 'TIR transit procedure', 'Douanevervoer onder het TIR-regime.', 'UNECE TIR-verdrag (1975)'),
('D16.4', 2, 'Trade document standards', 'Gestandaardiseerde handelsdocumenten.', 'UN/CEFACT-aanbevelingen'),
('D16.5', 1, 'Supply chain impact assessment', 'Nadelige gevolgen in de keten beoordelen.', 'UNGP 18'),
('D16.5', 2, 'Leverage and remediation', 'Invloed aanwenden en herstellen.', 'UNGP 19'),
('D16.6', 1, 'Controlled waste movements', 'Beheerste overbrenging van gevaarlijk afval.', 'Verdrag van Bazel art. 4'),
('D16.6', 2, 'Environmentally sound management', 'Milieuverantwoord beheer van afvalstromen.', 'Verdrag van Bazel'),
-- D17 security (GA-res. 57/239 en 45/95)
('D17.1', 1, 'Risk assessment', 'Periodieke beoordeling van beveiligingsrisico''s.', 'GA-res. 57/239 element f'),
('D17.1', 2, 'Security management', 'Samenhangend beheer van de beveiliging.', 'GA-res. 57/239 element h'),
('D17.2', 1, 'Timely detection and response', 'Incidenten tijdig zien en afhandelen.', 'GA-res. 57/239 element c'),
('D17.2', 2, 'Cooperation and information sharing', 'Samenwerken en informatie delen bij incidenten.', 'GA-res. 57/239 element c'),
('D17.3', 1, 'Continuity provisions', 'Uitwijk en back-up voor doorwerken.', 'Sendai-raamwerk prioriteit 3'),
('D17.5', 1, 'Security by design', 'Beveiliging als ontwerpuitgangspunt.', 'GA-res. 57/239 element g'),
('D17.6', 1, 'Reassessment', 'Beveiliging opnieuw beoordelen en bijstellen.', 'GA-res. 57/239 element i'),
('D17.7', 1, 'Awareness', 'Bewustzijn van risico''s en maatregelen.', 'GA-res. 57/239 element a'),
('D17.7', 2, 'Responsibility', 'Ieders verantwoordelijkheid voor eigen systemen.', 'GA-res. 57/239 element b'),
('D17.8', 1, 'Encryption in design', 'Versleuteling als onderdeel van het ontwerp.', 'GA-res. 57/239 element g'),
('D17.9', 1, 'Access as security management', 'Toegangsbeheer als beheersmaatregel.', 'GA-res. 57/239 element h'),
('D17.10', 1, 'Secured communications by design', 'Beveiligde communicatie en sterke authenticatie.', 'GA-res. 57/239 element g'),
('D17.11', 1, 'Security of personal data files', 'Beveiliging van persoonsbestanden.', 'GA-res. 45/95 beginsel 7'),
('D17.11', 2, 'Supervision', 'Onafhankelijk toezicht op de verwerking.', 'GA-res. 45/95 beginsel 8')
ON CONFLICT DO NOTHING;

COMMIT;
