"""Pure, deterministic renderers for auto-onboarding artifacts.

Nothing here touches the filesystem, the network, Docker or Authentik — every
function maps a Manifest (or a list of them) to a string or plain data. That
keeps the core trivially unit-testable without a running stack; the side
effects live in register.py (files) and deployer.py (the VM).
"""
from __future__ import annotations

import yaml

from manifest import Manifest

# Marker so humans (and the portal) can tell an apps.d entry was machine-written.
GENERATED_BY = "appsync"

_NGINX_HEADER = """# AUTO-GENERATED by appsync — do not edit by hand.
# One server block per auto-onboarded app. Source of truth: apps.d/*.yaml.
# Every request is validated by Authentik forward auth (snippets/forward-auth.conf).
"""

_NGINX_BLOCK = """\
server {{
    listen 443 ssl;
    http2 on;
    server_name {subdomain}.${{BASE_DOMAIN}};
    include /etc/nginx/snippets/ssl.conf;
    set $app_upstream http://{upstream};
    include /etc/nginx/snippets/forward-auth.conf;
}}
"""


def app_entry(m: Manifest) -> dict:
    """The portal tile entry, written to apps.d/<id>.yaml."""
    return {
        "id": m.id,
        "name": m.name,
        "description": m.description,
        "subdomain": m.subdomain,
        "roles": list(m.roles),
        "status": "active",
        "generated_by": GENERATED_BY,
    }


def app_entry_yaml(m: Manifest) -> str:
    """apps.d/<id>.yaml content: a one-app catalog fragment ({"apps": [entry]})."""
    doc = {"apps": [app_entry(m)]}
    body = yaml.safe_dump(doc, sort_keys=False, allow_unicode=True)
    return f"# AUTO-GENERATED by appsync — edits are overwritten on the next sync.\n{body}"


def nginx_block(m: Manifest) -> str:
    """A single nginx server block for one app."""
    return _NGINX_BLOCK.format(subdomain=m.subdomain, upstream=m.resolved_upstream())


def nginx_file(manifests: list[Manifest]) -> str:
    """The full 50-autoapps.conf.template, deterministically ordered by id."""
    ordered = sorted(manifests, key=lambda m: m.id)
    blocks = "\n".join(nginx_block(m) for m in ordered)
    return _NGINX_HEADER + ("\n" + blocks if blocks else "")


def merge_subdomains(existing: list[str], manifests: list[Manifest]) -> list[str]:
    """Union of existing extra-SAN subdomains with all auto-app subdomains.

    Returns a deduplicated, sorted list so the cert marker is stable (the cert
    only regenerates when the set actually changes).
    """
    wanted = set(s for s in existing if s) | {m.subdomain for m in manifests}
    return sorted(wanted)


def authentik_blueprint(m: Manifest, base_domain: str = "globaal.be") -> str:
    """A declarative Authentik blueprint: proxy provider + application + group
    binding, mirroring scripts/add-*.py.

    Dropped into a watched blueprint directory, Authentik applies it
    idempotently (identifiers make re-applies safe). The base domain is baked
    into the external hosts rather than relying on blueprint interpolation.
    """
    host = f"https://{m.subdomain}.{base_domain}"
    proxy_id = f"appsync-{m.id}-proxy"
    app_id = f"appsync-{m.id}-app"
    group_id = f"appsync-group-{m.id}"

    entries: list[dict] = [
        {
            "model": "authentik_core.group",
            "id": group_id,
            "identifiers": {"name": m.id},
            "attrs": {"name": m.id},
        },
        {
            "model": "authentik_providers_proxy.proxyprovider",
            "id": proxy_id,
            "identifiers": {"name": f"{m.id}-proxy"},
            "attrs": {
                "name": f"{m.id}-proxy",
                "mode": "forward_single",
                "external_host": host,
                "authorization_flow": "!Find [authentik_flows.flow, "
                "[slug, default-provider-authorization-implicit-consent]]",
            },
        },
        {
            "model": "authentik_core.application",
            "id": app_id,
            "identifiers": {"slug": m.id},
            "attrs": {
                "name": m.name,
                "slug": m.id,
                "provider": f"!KeyOf {proxy_id}",
                "meta_launch_url": host,
            },
        },
        {
            "model": "authentik_policies.policybinding",
            "identifiers": {
                "target": f"!KeyOf {app_id}",
                "group": f"!KeyOf {group_id}",
                "order": 0,
            },
        },
    ]

    if m.maker:
        entries.append(
            {
                "model": "authentik_core.user",
                "identifiers": {"username": m.maker},
                "attrs": {"groups": [f"!KeyOf {group_id}"]},
                # Attach the group to the existing user; "present" is a no-op
                # create-or-update so re-applies stay idempotent.
                "state": "present",
            }
        )

    blueprint = {
        "version": 1,
        "metadata": {"name": f"appsync: {m.id}"},
        "entries": entries,
    }
    body = yaml.safe_dump(blueprint, sort_keys=False, allow_unicode=True)
    return f"# AUTO-GENERATED by appsync for app '{m.id}'.\n{body}"
