"""Idempotent application of generated artifacts onto the repo working tree.

The single source of truth is ``apps.d/<id>.yaml`` (one file per auto-onboarded
app). Everything else — the nginx server blocks and the extra cert SANs — is
rebuilt deterministically from whatever ``apps.d/`` currently contains, so the
output never drifts and rollback is "delete the file and re-run".
"""
from __future__ import annotations

from pathlib import Path

import yaml

import generator
from manifest import Manifest, load_manifest

# Paths relative to the repo root.
APPS_D = "apps.d"
NGINX_AUTO_FILE = "nginx/templates/50-autoapps.conf.template"
CERT_EXTRA_FILE = "certs/extra-subdomains"
BLUEPRINTS_DIR = "authentik/blueprints"


class Registry:
    """Reads/writes the auto-onboarding state under a repo root."""

    def __init__(self, repo_root: str | Path, base_domain: str = "globaal.be"):
        self.root = Path(repo_root)
        self.base_domain = base_domain

    # --- paths -------------------------------------------------------------
    def _apps_d(self) -> Path:
        return self.root / APPS_D

    def _entry_path(self, app_id: str) -> Path:
        return self._apps_d() / f"{app_id}.yaml"

    # --- reads -------------------------------------------------------------
    def list_manifests(self) -> list[Manifest]:
        """Reconstruct Manifests from every apps.d/<id>.yaml on disk."""
        out: list[Manifest] = []
        d = self._apps_d()
        if not d.is_dir():
            return out
        for path in sorted(d.glob("*.yaml")):
            doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
            for entry in doc.get("apps", []):
                # apps.d entries carry no port/upstream (the tile doesn't need
                # them); reuse the saved sidecar if present, else default.
                meta = entry.get("_appsync", {})
                m = load_manifest(
                    {
                        "id": entry["id"],
                        "name": entry.get("name"),
                        "subdomain": entry.get("subdomain"),
                        "description": entry.get("description"),
                        "roles": entry.get("roles"),
                        "port": meta.get("port", 8080),
                        "upstream": meta.get("upstream"),
                        "maker": meta.get("maker"),
                    },
                    repo_name=entry["id"],
                )
                out.append(m)
        return out

    # --- writes ------------------------------------------------------------
    def apply(self, m: Manifest) -> dict[str, str]:
        """Onboard (or update) one app. Returns a map of artifact -> path."""
        written: dict[str, str] = {}

        # 1. The portal tile fragment (source of truth). Persist port/upstream/
        #    maker in a sidecar key so list_manifests() can rebuild faithfully.
        self._apps_d().mkdir(parents=True, exist_ok=True)
        doc = yaml.safe_load(generator.app_entry_yaml(m)) or {}
        doc["apps"][0]["_appsync"] = {
            "port": m.port,
            "upstream": m.upstream,
            "maker": m.maker,
        }
        header = "# AUTO-GENERATED by appsync — edits are overwritten on the next sync.\n"
        entry_path = self._entry_path(m.id)
        entry_path.write_text(
            header + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True),
            encoding="utf-8",
        )
        written["tile"] = str(entry_path.relative_to(self.root))

        # 2..4 derive from the full apps.d set (so removing an app cleans up too).
        manifests = self.list_manifests()
        written.update(self._rebuild_derived(manifests))
        # The Authentik blueprint is per-app.
        bp_dir = self.root / BLUEPRINTS_DIR
        bp_dir.mkdir(parents=True, exist_ok=True)
        bp_path = bp_dir / f"{m.id}.yaml"
        bp_path.write_text(
            generator.authentik_blueprint(m, self.base_domain), encoding="utf-8"
        )
        written["blueprint"] = str(bp_path.relative_to(self.root))
        return written

    def remove(self, app_id: str) -> None:
        """Roll back one app: drop its files and rebuild the derived outputs."""
        self._entry_path(app_id).unlink(missing_ok=True)
        (self.root / BLUEPRINTS_DIR / f"{app_id}.yaml").unlink(missing_ok=True)
        self._rebuild_derived(self.list_manifests())

    def _rebuild_derived(self, manifests: list[Manifest]) -> dict[str, str]:
        written: dict[str, str] = {}

        nginx_path = self.root / NGINX_AUTO_FILE
        nginx_path.parent.mkdir(parents=True, exist_ok=True)
        nginx_path.write_text(generator.nginx_file(manifests), encoding="utf-8")
        written["nginx"] = NGINX_AUTO_FILE

        # The extra-SAN file is an appsync-owned artifact rebuilt purely from
        # apps.d, so removing an app also drops its SAN. Hand-maintained
        # subdomains belong in CERT_SUBDOMAINS (env), not here.
        subdomains = generator.merge_subdomains([], manifests)
        cert_path = self.root / CERT_EXTRA_FILE
        cert_path.parent.mkdir(parents=True, exist_ok=True)
        cert_path.write_text(
            "".join(f"{s}\n" for s in subdomains), encoding="utf-8"
        )
        written["cert"] = CERT_EXTRA_FILE
        return written
